### ISSUE TITLE
python example image generation, pass through resolution & pixel matrix string

### ISSUE THREAD

**Issue by andykais** [andykais/painting-base2#3]

**Comment by courtfiala** [comment]
Currently can pass in pixel matrix filename
Will figure out logistics of passing in whole matrix as a string & implement if it will work well

**Comment by courtfiala** [comment]
Matrix size for any image larger than about 100x100 is too large for command line input
"bash: /home/court/.anaconda2/bin/python: Argument list too long"

**Comment by andykais** [comment]
did you try 

```
# create-image.py [width] [height] [binary-matrix-as-string]
./create-image.py 100 100 "10001010001000100010..."
```
